export const SET_LIST_DETAIL = 'SET_LIST_DETAIL'

export const SET_ROUTER_ANIM = 'SET_ROUTER_ANIM'

export const SET_SELECT_SIZE_COLOR = 'SET_SELECT_SIZE_COLOR'

export const SET_SPECIFICATION_DATA = 'SET_SPECIFICATION_DATA'

export const SET_SELECT_SPECIFICATION = 'SET_SELECT_SPECIFICATION'

export const SET_SWIPER_FULL = 'SET_SWIPER_FULL'

export const SET_SWIPER_FULL_INDEX = 'SET_SWIPER_FULL_INDEX'

export const SET_ALERT_HINT = 'SET_ALERT_HINT'

export const SET_STATE_ORDER = 'SET_STATE_ORDER'
