export const SET_ROUTER_ANIM = 'SET_ROUTER_ANIM'

export const SET_SELECT_SIZE_COLOR = 'SET_SELECT_SIZE_COLOR'

export const SET_SWIPER_FULL = 'SET_SWIPER_FULL'

export const SET_SWIPER_FULL_INDEX = 'SET_SWIPER_FULL_INDEX'
